name: edmund-agent-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.3
  - pip:
    - openai>=1.12.0
    - azure-identity>=1.15.0
    - azure-keyvault-secrets>=4.7.0
    - azure-ai-ml>=1.12.0
    - requests>=2.31.0
    - pyyaml>=6.0
    - jsonschema>=4.20.0
    - python-dotenv>=1.0.0
    - flask>=3.0.0
    - gunicorn>=21.2.0